### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by SandyChapman** [carbon-io/carbon-io#38]
Hey carbon.io maintainers. I've been watching this project for a while now and I'm wondering if this is ready for production usage. I think I saw a caveat earlier to avoid prod use until 1.0. Is that still the case? Is there a timeline on when that milestone will be achieved? Thanks!

**Comment by willshulman** [comment]
Hi Sandy-

I would say it depends on how adventurous you are feeling :). We have cautioned against broad production use because (a) we have not done much performance testing and b) the docs still have areas that are incomplete. However, we use it internally at mLab for production and do consider it to be pretty stable, particularly the 0.7 version (latest). 

Hope that answer helps. If you do decide to use it, we welcome your feedback and any bug reports you might have. 

-will

**Comment by SandyChapman** [comment]
@willshulman : Thanks, Will. We will take this into consideration. Looking forward to 1.0! 👍
